import {questions,demands,initialState,restore,evaluate} from './game.js?v=context-2';
const key='1919-prototype-v1';let state=initialState(),notice='',feedback=null,mapOpen=false,resetOpen=false;
try{state=restore(localStorage.getItem(key));}catch{notice='이 브라우저에서는 기록을 저장할 수 없어요. 현재 탭에서는 계속할 수 있습니다.';}
const app=document.querySelector('#app');
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{notice='진행 기록 저장이 제한되어 있어요. 현재 탭에서 계속 플레이할 수 있습니다.';}}
function render(focus){
 app.innerHTML=`<header class="mast"><a href="#" data-action="home" class="brand">1919<span>목소리 조사단</span></a><div class="header-right"><span class="edition">첫 번째 목소리 · 체험판</span><button class="quiet" data-action="map">변화 지도 <span class="count">${state.completed?'1':'0'}/1</span></button></div></header>
 ${notice?`<p class="storage" role="status">${notice}</p>`:''}
 ${state.screen==='intro'?intro():play()}
 <footer><span>역사를 읽는 다른 방법, 사람들의 목소리에서 시작합니다.</span><button class="quiet" data-action="reset">처음부터</button></footer>
 ${mapOpen?map():''}${resetOpen?reset():''}`;
 bind();if(focus)document.querySelector(focus)?.focus();
}
function intro(){return `<main class="intro"><div class="eyebrow">EUROPE AFTER THE WAR · 1919</div><div class="intro-grid"><section><p class="issue">전쟁은 끝났다. 질문은 시작됐다.</p><h1>1919년,<br>당신이라면<br><em>무엇을 요구하시겠습니까?</em></h1><p class="lead">“전쟁 전의 세상으로<br>그대로 돌아갈 수는 없어.”</p><p class="description">당신은 세계 변화 조사단입니다.<br>사람들의 이야기를 듣고, 그들이 원하는 변화를 찾아보세요.</p><button class="primary" data-action="start">${state.heard.length||state.completed?'조사 이어하기':'첫 번째 목소리 듣기'} <span>↗</span></button><p class="small">한 장면 · 약 3~5분 · 점수와 시간 제한 없음</p></section><div class="poster" aria-hidden="true"><div class="poster-top">THE VOICES OF<br>A CHANGING WORLD</div><div class="year">19<br>19<span>전쟁 이후,<br>이름 없는 목소리들.</span></div><div class="poster-bottom">POLITICAL RIGHTS / A BETTER LIFE</div></div></div><div class="steps"><span><b>01</b> 질문하고</span><span><b>02</b> 근거를 찾고</span><span><b>03</b> 변화를 기록하세요</span></div></main>`;}
function play(){const done=state.screen==='complete';return `<main class="workspace"><div class="section-heading"><div><div class="eyebrow">FIELD NOTE · 01</div><h1 tabindex="-1" id="screen-title">${done?'첫 번째 목소리를 기록했습니다.':state.screen==='report'?'어떤 변화를 원하는 걸까요?':'그녀에게 질문해 보세요.'}</h1></div><span class="phase">${done?'조사 완료':state.screen==='report'?'02 · 조사 기록':'01 · 인터뷰'}</span></div><div class="play-grid"><section class="main-panel">${done?completion():state.screen==='report'?report():interview()}</section><aside class="notebook"><div class="eyebrow">YOUR NOTEBOOK</div><h2>조사 노트 <span>${state.heard.length}/3</span></h2><p class="muted">직접 들은 말이 판단의 근거가 됩니다.</p>${state.heard.length?state.heard.map(id=>{let q=questions.find(q=>q.id===id);return `<article class="note"><span>${q.topic}</span><p>“${q.answer}”</p></article>`;}).join(''):'<div class="empty-note"><span>✎</span><p>질문을 고르면<br>이곳에 발언이 쌓여요.</p></div>'}<div class="map-teaser"><span>변화 지도</span><strong>${state.completed?'여성 참정권':'아직 기록한 요구가 없어요'}</strong><button class="text-button" data-action="map">지도 펼치기 ↗</button></div></aside></div></main>`;}
function person(){return `<div class="person"><div class="avatar" aria-hidden="true">여성<br>노동자</div><div><span class="eyebrow">전쟁을 겪은 사람</span><h2>공장에서 일했던 여성</h2><span class="small">특정 국가를 지정하지 않은 재구성 인물</span></div></div>`;}
function background(){return `<section class="scene-background" aria-labelledby="background-title"><h3 id="background-title">이 사람을 만나기 전에</h3><p>1919년, 전쟁이 끝난 뒤 유럽의 한 공업 도시입니다. 남성들이 전쟁터에 나간 동안 공장에서 일했던 여성을 만납니다.</p><p>그녀는 계속 일해서 생활비를 마련하고 싶습니다. 하지만 이 이야기 속 여성은 대표를 뽑는 선거에 참여할 권리가 없습니다. 일자리와 생활에 영향을 주는 결정에도 자신의 목소리가 빠져 있다고 느낍니다.</p><p class="context-question">여러 걱정 가운데, 그녀는 어떤 변화를 더 바랄까요?</p></section>`;}
function interview(){let q=questions.find(q=>q.id===state.active);return `${person()}${background()}<blockquote aria-live="polite" aria-atomic="true">“${q?q.answer:'전쟁 동안 공장에서 일했어요. 그런데 전쟁이 끝나니 우리에게 다시 예전처럼 살라고 하네요.'}”</blockquote><div class="prompt"><h3>무엇이 궁금한가요?</h3><p>질문에는 정답이 없어요. 이야기를 충분히 들어보세요.</p></div><div class="questions">${questions.map((q,i)=>`<button class="question ${state.active===q.id?'selected':''}" data-question="${q.id}" aria-pressed="${state.active===q.id}"><span class="question-number">0${i+1}</span><span>${q.label}</span><small>${state.heard.includes(q.id)?'들은 질문 ✓':'물어보기 ↗'}</small></button>`).join('')}</div><div class="panel-bottom"><span class="small">들은 질문은 다시 눌러 확인할 수 있어요.</span><button class="primary" data-action="report">조사 기록하기 →</button></div>`;}
function report(){return `${person()}${background()}<p class="task">그녀가 <strong>더 바라는 변화</strong>는 무엇으로 들렸나요?<br>발언을 근거로 생각을 정리하고, 인물에게 확인해 보세요.</p><fieldset><legend><span>1</span> 어떤 변화를 더 원하는 것 같나요?</legend><div class="choices">${demands.map(d=>`<label class="choice ${state.demand===d.id?'chosen':''}"><input type="radio" name="demand" value="${d.id}" ${state.demand===d.id?'checked':''}><span><strong>${d.label}</strong><small>${d.detail}</small></span></label>`).join('')}</div></fieldset><fieldset><legend><span>2</span> 그 판단을 뒷받침하는 발언을 고르세요</legend>${state.heard.length?state.heard.map(id=>{let q=questions.find(q=>q.id===id);return `<label class="choice evidence ${state.evidence===id?'chosen':''}"><input type="radio" name="evidence" value="${id}" ${state.evidence===id?'checked':''}><span>“${q.answer}”</span></label>`;}).join(''):'<p class="muted">아직 들은 발언이 없어요. 인터뷰로 돌아가 질문해 주세요.</p>'}</fieldset><div id="feedback" role="status" aria-live="polite">${feedback?`<div class="feedback ${feedback.kind==='conversation'?'conversation':''}"><span class="feedback-speaker">${feedback.kind==='conversation'?'여성 노동자의 답변':'조사 안내'}</span><strong>${feedback.title}</strong><p>${feedback.text}</p>${feedback.kind==='conversation'?'<span class="response-note">이야기를 듣고 생각을 보완해도 좋아요.</span>':''}</div>`:''}</div><div class="panel-bottom"><button class="text-button" data-action="interview">← 더 물어보기</button><button class="primary" data-action="submit">인물에게 확인하기 ↗</button></div>`;}
function completion(){return `<div class="complete-badge">조사 완료 ✓</div><h2 class="complete-title">“우리 삶을 결정하는 정치에<br>여성도 참여하고 싶어요.”</h2><blockquote class="confirmation">“일자리와 생활도 중요하지만, 저는 정치에 제 목소리를 낼 권리를 더 원해요.”</blockquote><p class="muted">이 사람이 더 바라는 요구를 근거와 함께 기록했어요. 일자리와 생활에 대한 걱정도 함께 들어봤습니다.</p><div class="concept"><span>수집한 요구</span><h3>여성 참정권</h3><div>↓</div><p>정치 참여 확대</p><div>↓</div><strong>민주주의의 확산</strong></div><p class="historical">여성의 정치 참여 권리는 나라와 시기에 따라 점차 확대되었습니다. 이 인물의 발언은 학습을 위한 재구성입니다.</p><button class="primary" data-action="map">나의 변화 지도 확인하기 ↗</button><div class="next-note"><span class="eyebrow">다음 조사에서는</span><p>선거가 있어도, 모두가 참여할 수 있을까요?</p><small>현재는 첫 인물만 플레이할 수 있는 프로토타입입니다.</small></div>`;}
function map(){return `<dialog open class="overlay" aria-modal="true" aria-labelledby="map-title"><div class="modal"><button class="close" data-action="close" aria-label="지도 닫기">✕</button><div class="eyebrow">MAP OF CHANGE</div><h2 id="map-title" tabindex="-1">나의 1919년 변화 지도</h2><p class="muted">목소리 하나에서 발견한 변화</p><div class="map-columns"><section><h3>정치 참여의 확대</h3>${state.completed?'<div class="map-card"><span>01 · 여성 노동자</span><h4>여성 참정권</h4><p>“대표를 뽑을 권리는 없어요.”</p></div>':'<div class="map-empty">이곳에 요구 카드를 모읍니다.</div>'}<strong class="map-concept">${state.completed?'민주주의의 확산':'???'}</strong></section><section><h3>경제적 평등의 요구</h3><div class="map-empty">다음 인물들의 목소리가<br>더해질 자리예요.</div><strong class="map-concept">???</strong></section></div><p class="historical">정치적 권리와 더 나은 경제적 삶은 함께 요구할 수 있습니다. 이후 장면에서 두 요구의 관계를 탐색합니다.</p><button class="primary" data-action="close">${state.completed?'조사 결과로 돌아가기':'조사 계속하기'} →</button></div></dialog>`;}
function reset(){return `<dialog open class="overlay" aria-modal="true" aria-labelledby="reset-title"><div class="modal reset-modal"><h2 id="reset-title" tabindex="-1">처음부터 조사할까요?</h2><p>이 체험판의 대화와 조사 기록이 초기화됩니다.</p><div class="panel-bottom"><button class="quiet" data-action="cancel-reset">계속하기</button><button class="primary" data-action="confirm-reset">처음부터 시작</button></div></div></dialog>`;}
function bind(){app.querySelectorAll('[data-action]').forEach(el=>el.onclick=e=>{e.preventDefault();let a=el.dataset.action;
 if(a==='start'){state.screen=state.completed?'complete':state.heard.length&&state.screen==='intro'?'interview':state.screen==='intro'?'interview':state.screen;}
 if(a==='home'){state.screen='intro';}if(a==='report'){state.screen='report';feedback=null;}if(a==='interview'){state.screen='interview';feedback=null;}
 if(a==='submit'){feedback=evaluate(state);if(feedback.ok){state.completed=true;state.screen='complete';feedback=null;}}
 if(a==='map')mapOpen=true;if(a==='close')mapOpen=false;if(a==='reset')resetOpen=true;if(a==='cancel-reset')resetOpen=false;if(a==='confirm-reset'){state=initialState();resetOpen=false;mapOpen=false;feedback=null;}
 save();render(mapOpen?'#map-title':resetOpen?'#reset-title':a==='close'?'[data-action="map"]':a==='cancel-reset'?'[data-action="reset"]':'#screen-title');
 });app.querySelectorAll('[data-question]').forEach(el=>el.onclick=()=>{state.active=el.dataset.question;if(!state.heard.includes(state.active))state.heard.push(state.active);save();render(`[data-question="${state.active}"]`);});app.querySelectorAll('input[type="radio"]').forEach(el=>el.onchange=()=>{state[el.name]=el.value;feedback=null;save();render(`input[name="${el.name}"][value="${el.value}"]`);});
 const dialog=app.querySelector('dialog');if(dialog)dialog.addEventListener('keydown',e=>{if(e.key==='Escape'){mapOpen=false;resetOpen=false;render('[data-action="map"]');}if(e.key==='Tab'){const items=[...dialog.querySelectorAll('button,input,a[href]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||!items.includes(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!items.includes(document.activeElement))){e.preventDefault();first.focus();}}});
}
render();
