import {questions,demands,initialState,restore,evaluate,canRecord,recordedDemand} from './game.js';
const key='1919-prototype-v1';let state=initialState(),notice='',feedback=null,mapOpen=false,resetOpen=false;
try{state=restore(localStorage.getItem(key));}catch{notice='이 브라우저에서는 기록을 저장할 수 없어요. 현재 탭에서는 계속할 수 있습니다.';}
const app=document.querySelector('#app');
const sceneArtwork='assets/woman-worker.webp';
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{notice='진행 기록 저장이 제한되어 있어요. 현재 탭에서 계속 플레이할 수 있습니다.';}}
function render(focus){
 app.innerHTML=`<header class="mast"><a href="#" data-action="home" class="brand">1919<span>목소리 조사단</span></a><div class="header-right"><span class="edition">첫 번째 목소리 · 체험판</span><button class="quiet" data-action="map">변화 지도 <span class="count">${state.completed?'1':'0'}/1</span></button></div></header>
 ${notice?`<p class="storage" role="status">${notice}</p>`:''}
 ${state.screen==='intro'?intro():play()}
 <footer><span>@BONSSAM 보은쌤과 함께하는 역사 수업</span><button class="quiet" data-action="reset">처음부터</button></footer>
 ${mapOpen?map():''}${resetOpen?reset():''}`;
 bind();if(focus)document.querySelector(focus)?.focus();
}
function intro(){return `<main class="intro"><div class="eyebrow">EUROPE AFTER THE WAR · 1919</div><div class="intro-grid"><section><p class="issue">전쟁은 끝났다. 질문은 시작됐다.</p><h1>1919년,<br>당신이라면<br><em>무엇을 요구하시겠습니까?</em></h1><p class="lead">“전쟁 전의 세상으로<br>그대로 돌아갈 수는 없어.”</p><p class="description">당신은 세계 변화 조사단입니다.<br>사람들의 이야기를 듣고, 그들이 원하는 변화를 찾아보세요.</p><button class="primary" data-action="start">${state.heard.length||state.completed?'조사 이어하기':'첫 번째 목소리 듣기'} <span>↗</span></button><p class="small">현재는 여성 노동자 한 장면 · 약 3~5분</p><p class="preview-scope">팽크허스트와 다른 사람들의 이야기는 준비 중입니다.</p></section><figure class="intro-art"><img src="${sceneArtwork}" alt="1919년의 공장 앞에 서 있는 여성 노동자의 수업용 삽화" fetchpriority="high"><figcaption><span>첫 번째 목소리</span><strong>전쟁 뒤, 공장 앞에서</strong><small>수업용 재구성 삽화</small></figcaption></figure></div><div class="steps"><span><b>01</b> 질문하고</span><span><b>02</b> 근거를 찾고</span><span><b>03</b> 나의 발견을 기록하세요</span></div></main>`;}
function play(){const done=state.screen==='complete',record=recordedDemand(state);return `<main class="workspace"><div class="section-heading"><div><div class="eyebrow">FIELD NOTE · 01</div><h1 tabindex="-1" id="screen-title">${done?'당신이 발견한 요구를 기록했습니다.':state.screen==='report'?'어떤 요구를 기록할까요?':'그녀에게 질문해 보세요.'}</h1></div><span class="phase">${done?'조사 완료':state.screen==='report'?'02 · 나의 발견':'01 · 인터뷰'}</span></div><div class="play-grid"><section class="main-panel">${done?completion():state.screen==='report'?report():interview()}</section><aside class="notebook"><div class="eyebrow">YOUR NOTEBOOK</div><h2>조사 노트 <span>${state.heard.length}/3</span></h2><p class="muted">직접 들은 말이 판단의 근거가 됩니다.</p>${state.heard.length?state.heard.map(id=>{let q=questions.find(q=>q.id===id);return `<article class="note"><span>${q.topic}</span><p>“${q.answer}”</p></article>`;}).join(''):'<div class="empty-note"><span>✎</span><p>질문을 고르면<br>이곳에 발언이 쌓여요.</p></div>'}<div class="map-teaser"><span>변화 지도</span><strong>${record?record.card:'아직 기록한 요구가 없어요'}</strong><button class="text-button" data-action="map">지도 펼치기 ↗</button></div></aside></div></main>`;}
function person(){return `<div class="person"><img class="portrait" src="${sceneArtwork}" alt="공장에서 일했던 여성 노동자"><div><span class="eyebrow">전쟁을 겪은 사람</span><h2>공장에서 일했던 여성</h2><span class="small">특정 국가를 지정하지 않은 재구성 인물</span></div></div>`;}
function background(){return `<section class="scene-background" aria-labelledby="background-title"><h3 id="background-title">이 사람을 만나기 전에</h3><p>1919년, 전쟁이 끝난 유럽의 공업 도시. 전쟁터로 떠난 사람들을 대신해 공장에서 일했던 여성입니다.</p><div class="context-facts"><span>공장 일로 마련하는 생활비</span><span>불안한 전후 일자리</span><span>아직 없는 선거 참여 권리</span></div><p class="context-question">생활과 정치, 그녀는 어떤 변화를 바랄까요?</p></section>`;}
function interview(){let q=questions.find(q=>q.id===state.active);return `${person()}<figure class="scene-art"><img src="${sceneArtwork}" alt="공장과 여성 노동자들의 모습. 역사적 상황을 재구성한 삽화"><figcaption>전쟁 이후, 유럽의 한 공장 · 수업용 재구성</figcaption></figure>${background()}<blockquote aria-live="polite" aria-atomic="true">“${q?q.answer:'전쟁 중에는 전쟁터로 떠난 사람들을 대신해 공장에서 일했어요. 그 일로 가족의 생활비도 마련했죠. 그런데 전쟁이 끝난 지금도 저는 나라의 대표를 뽑는 데 참여할 수 없어요. 일자리와 생활에 영향을 주는 결정인데, 제 의견은 들리지 않는 것 같아요.'}”</blockquote><div class="prompt"><h3>무엇이 궁금한가요?</h3><p>세 이야기를 듣고, 당신이 주목한 요구를 기록해 보세요.</p></div><div class="questions">${questions.map((q,i)=>`<button class="question ${state.active===q.id?'selected':''}" data-question="${q.id}" aria-pressed="${state.active===q.id}"><span class="question-number">0${i+1}</span><span>${q.label}</span><small>${state.heard.includes(q.id)?'들은 질문 ✓':'물어보기 ↗'}</small></button>`).join('')}</div><div class="panel-bottom"><span class="small" id="interview-progress" role="status">${canRecord(state)?'세 이야기를 모두 들었어요. 이제 생각을 정리해 보세요.':`이야기 ${state.heard.length}/${questions.length} · 모두 들은 뒤 생각을 정리할 수 있어요.`}</span><button class="primary" data-action="report" aria-describedby="interview-progress" ${canRecord(state)?'':'disabled'}>${canRecord(state)?'그녀가 바라는 변화 정리하기 →':`이야기 ${state.heard.length}/${questions.length} · 모두 들어보세요`}</button></div>`;}
function report(){return `${person()}<p class="task">한 사람이 여러 변화를 바랄 수 있어요.<br><strong>당신이 주목한 요구</strong>와 그 이유가 된 발언을 연결해 보세요.</p><div class="choice-note">그녀는 정치 참여를 가장 바라고 있지만, 일자리와 생활의 걱정도 실제 요구예요. 당신이 고른 요구를 그 발언과 연결해 기록해 보세요.</div><fieldset><legend><span>1</span> 어떤 요구를 기록하고 싶나요?</legend><div class="choices">${demands.map(d=>`<label class="choice ${state.demand===d.id?'chosen':''}"><input type="radio" name="demand" value="${d.id}" ${state.demand===d.id?'checked':''}><span><strong>${d.label}</strong><small>${d.detail}</small></span></label>`).join('')}</div></fieldset><fieldset><legend><span>2</span> 그 요구와 이어지는 발언을 고르세요</legend>${state.heard.map(id=>{let q=questions.find(q=>q.id===id);return `<label class="choice evidence ${state.evidence===id?'chosen':''}"><input type="radio" name="evidence" value="${id}" ${state.evidence===id?'checked':''}><span>“${q.answer}”</span></label>`;}).join('')}</fieldset><div id="feedback" role="status" aria-live="polite">${feedback?`<div class="feedback conversation"><span class="feedback-speaker">${feedback.kind==='conversation'?'여성 노동자의 답변':'조사 안내'}</span><strong>${feedback.title}</strong><p>${feedback.text}</p></div>`:''}</div><div class="panel-bottom"><button class="text-button" data-action="interview">← 더 물어보기</button><button class="primary" data-action="submit">이 요구를 기록하기 ↗</button></div>`;}
function completion(){const record=recordedDemand(state),evidence=questions.find(q=>q.id===state.evidence);return `<div class="complete-badge">조사 완료 ✓</div>${person()}<p class="result-label">당신이 기록한 요구</p><h2 class="complete-title">${record.label}</h2><blockquote class="confirmation">“${record.response}”</blockquote><div class="concept ${record.area==='economic'?'economic-concept':''}"><span>변화 지도에 기록한 카드</span><h3>${record.card}</h3><div>↓</div><strong>${record.connection}</strong>${record.area==='political'?'<div>↓</div><p>민주주의의 확산</p>':'<p class="concept-note">정치에 참여하고 싶은 마음과<br>함께 바랄 수 있는 변화예요.</p>'}</div><details class="result-evidence"><summary>내가 연결한 발언 다시 보기</summary><p>“${evidence.answer}”</p></details><p class="historical">${record.area==='political'?'여성의 정치 참여 권리는 나라와 시기에 따라 점차 확대되었습니다.':'이 결과에는 선택한 경제적 요구가 기록됩니다. 그녀가 가장 바라는 정치적 권리와 함께 존재할 수 있어요.'}</p><div class="result-actions"><button class="primary" data-action="map">나의 변화 지도 확인하기 ↗</button><button class="text-button" data-action="revise">다른 요구도 살펴보기 →</button></div><div class="next-note"><span class="eyebrow">다음 목소리 · 준비 중</span><p>팽크허스트는 어떤 활동으로 여성의 정치적 권리를 요구했을까요?</p><small>현재는 여성 노동자 한 장면만 플레이할 수 있습니다.</small></div>`;}
function map(){const record=recordedDemand(state),card=record?`<div class="map-card" data-area="${record.area}"><span>01 · 여성 노동자</span><h4>${record.card}</h4><p>당신이 고른 요구와 발언을 기록했어요.</p></div>`:'';return `<dialog open class="overlay" aria-modal="true" aria-labelledby="map-title"><div class="modal"><button class="close" data-action="close" aria-label="지도 닫기">✕</button><div class="eyebrow">MAP OF CHANGE</div><h2 id="map-title" tabindex="-1">나의 1919년 변화 지도</h2><p class="muted">목소리 하나에서 당신이 발견한 변화</p><div class="map-columns"><section><h3>정치 참여의 확대</h3>${record?.area==='political'?card:'<div class="map-empty">정치 참여 요구가<br>들어올 자리예요.</div>'}<strong class="map-concept">${record?.area==='political'?'민주주의의 확산':'???'}</strong></section><section><h3>경제적 삶의 개선</h3>${record?.area==='economic'?card:'<div class="map-empty">경제적 요구가<br>들어올 자리예요.</div>'}<strong class="map-concept">${record?.area==='economic'?'일자리와 생활의 변화':'???'}</strong></section></div><p class="historical">정치적 권리와 더 나은 경제적 삶은 함께 요구할 수 있습니다. 이후 장면에서 사회주의의 뜻과 확산을 살펴볼 예정입니다.</p><button class="primary" data-action="close">${state.completed?'조사 결과로 돌아가기':'조사 계속하기'} →</button></div></dialog>`;}
function reset(){return `<dialog open class="overlay" aria-modal="true" aria-labelledby="reset-title"><div class="modal reset-modal"><h2 id="reset-title" tabindex="-1">처음부터 조사할까요?</h2><p>이 체험판의 대화와 조사 기록이 초기화됩니다.</p><div class="panel-bottom"><button class="quiet" data-action="cancel-reset">계속하기</button><button class="primary" data-action="confirm-reset">처음부터 시작</button></div></div></dialog>`;}
function bind(){app.querySelectorAll('[data-action]').forEach(el=>el.onclick=e=>{e.preventDefault();const a=el.dataset.action;
 if(a==='start')state.screen=state.completed?'complete':state.screen==='intro'?'interview':state.screen;
 if(a==='home')state.screen='intro';if(a==='report'){if(!canRecord(state))return;state.screen='report';feedback=null;}if(a==='interview'){state.screen='interview';feedback=null;}
 if(a==='submit'){feedback=evaluate(state);if(feedback.ok){state.completed=true;state.screen='complete';feedback=null;}}
 if(a==='revise'){state.completed=false;state.screen='report';feedback=null;}
 if(a==='map')mapOpen=true;if(a==='close')mapOpen=false;if(a==='reset')resetOpen=true;if(a==='cancel-reset')resetOpen=false;if(a==='confirm-reset'){state=initialState();resetOpen=false;mapOpen=false;feedback=null;}
 save();render(mapOpen?'#map-title':resetOpen?'#reset-title':a==='close'?'[data-action="map"]':a==='cancel-reset'?'[data-action="reset"]':'#screen-title');
 });app.querySelectorAll('[data-question]').forEach(el=>el.onclick=()=>{state.active=el.dataset.question;if(!state.heard.includes(state.active))state.heard.push(state.active);save();render(`[data-question="${state.active}"]`);});app.querySelectorAll('input[type="radio"]').forEach(el=>el.onchange=()=>{state[el.name]=el.value;feedback=null;save();render(`input[name="${el.name}"][value="${el.value}"]`);});
 const dialog=app.querySelector('dialog');if(dialog)dialog.addEventListener('keydown',e=>{if(e.key==='Escape'){mapOpen=false;resetOpen=false;render('[data-action="map"]');}if(e.key==='Tab'){const items=[...dialog.querySelectorAll('button,input,a[href]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&(document.activeElement===first||!items.includes(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!items.includes(document.activeElement))){e.preventDefault();first.focus();}}});
}
render();
