import test from 'node:test';
import assert from 'node:assert/strict';
import {scenes,initialState,chapter,canRecord,canVisit,allComplete,evaluate,getRecords,concepts,completeChapter,nextScene,visitScene,restore,availableProposals} from '../game.js';
const forms={woman:{demand:'vote',evidence:'vote'},pankhurst:{demand:'vote',action:'movement',impact:'gradual'},citizens:{system:'broad',reason:'participation'},peasant:{demand:'land',evidence:'land'},factory:{proposal:'coop',evidence:'ownership'},young:{political:'universal',economic:'living',politicalEvidence:'political',economicEvidence:'economic'}};
function prepare(state,id,form=forms[id]){const c=chapter(state,id);c.heard=scenes.find(s=>s.id===id).items.map(i=>i.id);c.form={...form};c.phase='activity';return c;}
function until(last=5,woman=forms.woman){const s=initialState();s.screen='play';for(let index=0;index<last;index++){s.sceneIndex=index;prepare(s,scenes[index].id,index===0?woman:forms[scenes[index].id]);assert.equal(completeChapter(s).ok,true);assert.equal(nextScene(s),true);}return s;}

test('distinct sources gate every scene; repeated or unrelated sources cannot bypass it',()=>{for(const scene of scenes){const s=initialState();s.sceneIndex=scenes.indexOf(scene);const c=chapter(s);c.form={...forms[scene.id]};for(let count=0;count<scene.items.length;count++){c.heard=scene.items.slice(0,count).map(i=>i.id);assert.equal(canRecord(s),false);assert.equal(evaluate(s).ok,false);}c.heard=Array(3).fill(scene.items[0].id);if(scene.items.length>1)assert.equal(canRecord(s),false);c.heard=scene.items.map(i=>i.id);assert.equal(canRecord(s),true);}});
test('all three first demands retain their own recorded card and area',()=>{for(const [demand,evidence,title,area] of [['jobs','work','일자리 유지','economic'],['support','work','생활 지원','economic'],['vote','priority','여성 참정권','political']]){const s=initialState();prepare(s,'woman',{demand,evidence});assert.equal(completeChapter(s).ok,true);const [record]=getRecords(s);assert.equal(record.title,title);assert.deepEqual(record.areas,[area]);assert.equal(restore(JSON.stringify(s)).chapters.woman.record.demand,demand);}});
test('revising a record does not lose or change its committed card before a valid submission',()=>{const s=until(1);visitScene(s,0);const c=prepare(s,'woman',{demand:'jobs',evidence:'vote'});assert.equal(completeChapter(s).ok,false);assert.equal(c.form.demand,'jobs');assert.equal(getRecords(s)[0].title,'여성 참정권');c.form.evidence='work';assert.equal(completeChapter(s).ok,true);assert.equal(getRecords(s).length,1);assert.equal(getRecords(s)[0].title,'일자리 유지');});
test('Pankhurst must connect political demand, collective activity and gradual expansion',()=>{const s=until(1);const c=prepare(s,'pankhurst');for(const patch of [{demand:'jobs'},{action:'work'},{impact:'all1918'},{impact:'alone'}]){c.form={...forms.pankhurst,...patch};assert.equal(completeChapter(s).ok,false);assert.equal(c.record,null);}c.form={...forms.pankhurst};assert.equal(completeChapter(s).ok,true);assert.equal(getRecords(s).length,2);});
test('two defensible reasons complete the citizens scene and create two unique voice records',()=>{for(const reason of ['participation','equal']){const s=until(2);const c=prepare(s,'citizens',{system:'broad',reason});assert.equal(completeChapter(s).ok,true);assert.deepEqual(getRecords(s).map(r=>r.id),['woman','pankhurst','citizen','german']);assert.equal(completeChapter(s).ok,true);assert.equal(getRecords(s).length,4);c.form.reason='wealth';assert.equal(evaluate(s).ok,false);c.form={system:'limited',reason};assert.equal(evaluate(s).ok,false);}});
test('peasant recall is independent of any previous game account and distinguishes other voices',()=>{const s=until(3);const c=prepare(s,'peasant',{demand:'food',evidence:'price'});assert.equal(completeChapter(s).ok,false);c.form={...forms.peasant};assert.equal(completeChapter(s).ok,true);assert.equal(getRecords(s).length,5);assert.equal(concepts(s).socialism,false);});
test('factory accepts two ownership proposals, distinguishes partial help and requires matching evidence',()=>{for(const proposal of ['coop','public']){const s=until(4);const c=prepare(s,'factory',{proposal:'pay',evidence:'wages'});const partial=completeChapter(s);assert.equal(partial.ok,false);assert.equal(partial.kind,'conversation');assert.match(partial.text,/임금뿐 아니라/);assert.equal(concepts(s).socialism,false);c.form={proposal,evidence:'wages'};assert.equal(completeChapter(s).ok,false);c.form.evidence='ownership';assert.equal(completeChapter(s).ok,true);assert.equal(concepts(s).socialism,true);assert.equal(getRecords(s).length,6);}});
test('young worker accepts many collected proposal combinations and produces one voice in both areas',()=>{const template=until(5,{demand:'jobs',evidence:'work'});const options=availableProposals(template);assert.equal(options.political.length,3);assert.ok(options.economic.some(p=>p.id==='jobs'));let count=0;for(const political of options.political){for(const economic of options.economic.filter(p=>p.id!=='land')){const s=restore(JSON.stringify(template));prepare(s,'young',{political:political.id,economic:economic.id,politicalEvidence:'political',economicEvidence:'economic'});assert.equal(completeChapter(s).ok,true);assert.equal(allComplete(s),true);const records=getRecords(s);assert.equal(records.length,7);assert.equal(new Set(records.map(r=>r.id)).size,7);assert.deepEqual(records.at(-1).areas,['political','economic']);assert.deepEqual(restore(JSON.stringify(s)),s);count++;}}assert.ok(count>=12);});
test('young worker rejects a missing demand, unrelated land proposal and swapped evidence without coercing choices',()=>{const s=until(5);const c=prepare(s,'young');for(const patch of [{economic:null},{economic:'land'},{politicalEvidence:'economic'},{economicEvidence:'political'},{political:'unknown'}]){c.form={...forms.young,...patch};assert.equal(completeChapter(s).ok,false);assert.equal(c.record,null);assert.equal(c.form.political,patch.political||'universal');}});
test('navigation cannot skip unfinished chapters and the final result leads to discovery',()=>{const s=initialState();assert.equal(canVisit(s,1),false);assert.equal(visitScene(s,5),false);assert.equal(nextScene(s),false);const full=until(5);prepare(full,'young');completeChapter(full);assert.equal(nextScene(full),true);assert.equal(full.screen,'discovery');assert.equal(visitScene(full,2),true);assert.equal(full.sceneIndex,2);assert.equal(getRecords(full).length,7);});
test('partial progress restores without fabricated completion, skipped chapters or an unlocked ending',()=>{const s=until(2);chapter(s).heard=['citizen'];chapter(s).form={system:'broad'};assert.deepEqual(restore(JSON.stringify(s)),s);const forged={...s,screen:'ending',sceneIndex:5};forged.chapters.factory.record={...forms.factory};const clean=restore(JSON.stringify(forged));assert.equal(clean.screen,'play');assert.equal(clean.sceneIndex,2);assert.equal(clean.chapters.factory.record,null);assert.equal(getRecords(clean).length,2);for(const raw of ['oops','null',JSON.stringify({...s,version:4}),JSON.stringify({...s,sceneIndex:99})])assert.deepEqual(restore(raw),initialState());});
test('legacy first-scene completion is migrated and can continue into Pankhurst',()=>{for(const version of [1,2]){const s=restore(JSON.stringify({version,screen:'complete',heard:['work','vote','priority'],active:'work',demand:'support',evidence:'work',completed:true}));assert.equal(s.version,3);assert.equal(chapter(s).phase,'result');assert.equal(getRecords(s)[0].title,'생활 지원');assert.equal(nextScene(s),true);assert.equal(s.sceneIndex,1);}const partial=restore(JSON.stringify({version:2,screen:'report',heard:['work'],demand:'jobs',evidence:'work',completed:false}));assert.equal(chapter(partial).phase,'explore');assert.deepEqual(chapter(partial).heard,['work']);});

test('revising an earlier requirement preserves a completed final plan based on the heard voice',()=>{for(const economic of ['jobs','support']){const s=until(5);prepare(s,'young',{...forms.young,economic});completeChapter(s);visitScene(s,0);prepare(s,'woman',{demand:'vote',evidence:'priority'});completeChapter(s);assert.equal(getRecords(s).length,7);assert.match(getRecords(s).at(-1).proposal,economic==='jobs'?/기회를 지키기/:/경제적 지원/);assert.equal(allComplete(restore(JSON.stringify(s))),true);}});
