import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,evaluate,restore,canRecord,recordedDemand} from '../game.js';
const ready=()=>({...initialState(),heard:['work','vote','priority'],demand:'vote',evidence:'vote'});
test('requires all three distinct stories before recording in any order',()=>{for(const heard of [[],['vote'],['work','vote'],['vote','vote','priority']]){assert.equal(canRecord({...ready(),heard}),false);assert.equal(evaluate({...ready(),heard}).ok,false);}assert.equal(canRecord({...ready(),heard:['priority','work','vote']}),true);assert.equal(evaluate(ready()).ok,true);});
test('economic needs can complete with matching evidence without becoming suffrage',()=>{for(const demand of ['jobs','support']){const s={...ready(),demand,evidence:'work'};const r=evaluate(s);assert.equal(r.ok,true);assert.equal(r.demandId,demand);assert.equal(s.demand,demand);assert.match(r.text,/제|저/);assert.doesNotMatch(r.title+r.text,/틀렸|우선순위를 다시/);const record=recordedDemand({...s,completed:true});assert.equal(record.id,demand);assert.equal(record.area,'economic');assert.notEqual(record.card,'여성 참정권');}});
test('unrelated evidence never changes the selected demand or creates a record',()=>{for(const demand of ['jobs','support']){const s={...ready(),demand,evidence:'vote'};assert.equal(evaluate(s).ok,false);assert.equal(s.demand,demand);assert.equal(recordedDemand(s),null);}});
test('a correct demand cannot pass with unrelated evidence',()=>assert.equal(evaluate({...ready(),evidence:'work'}).ok,false));
test('both political statements are valid evidence',()=>{assert.equal(evaluate(ready()).ok,true);assert.equal(evaluate({...ready(),evidence:'priority'}).ok,true);});
test('restores progress and rejects corrupt or incompatible saves',()=>{const s={...ready(),screen:'report'};assert.deepEqual(restore(JSON.stringify(s)),s);for(const raw of ['oops','null',JSON.stringify({...s,version:3}),JSON.stringify({...s,heard:['unknown']})])assert.deepEqual(restore(raw),initialState());});
test('migrates an old completed record and preserves each new branch on reload',()=>{const old={...ready(),version:1,screen:'complete',completed:true};assert.deepEqual(restore(JSON.stringify(old)),{...old,version:2});for(const demand of ['jobs','support']){const s={...ready(),screen:'complete',completed:true,demand,evidence:'work'};assert.deepEqual(restore(JSON.stringify(s)),s);assert.equal(recordedDemand(restore(JSON.stringify(s))).id,demand);}});
test('a forged completion with missing or unrelated evidence returns to the activity',()=>{for(const patch of [{heard:['work']},{demand:'jobs',evidence:'vote'},{demand:null},{evidence:null}]){const s=restore(JSON.stringify({...ready(),screen:'complete',completed:true,...patch}));assert.equal(s.completed,false);assert.notEqual(s.screen,'complete');assert.equal(recordedDemand(s),null);}});

test('resumes an old incomplete report at interview without losing heard stories',()=>{const s={...ready(),screen:'report',heard:['vote']};const result=restore(JSON.stringify(s));assert.equal(result.screen,'interview');assert.deepEqual(result.heard,['vote']);assert.equal(result.demand,'vote');});
